package bot.constants

object ConstantsString {
    const val addLink = "Добавить ссылку"
    const val showLinks = "Показать доступные ссылки"
    const val selectConnectMethod = "Выберите метод подключения"
    const val databaseConnectionSsh = "Подключение по SSH"
    const val databaseConnectionString = "Подключение по строке подключения"
    const val databaseConnectionFile = "Подключение по файлу"
    const val databaseConnectionConstructor = "Конструктор соединения"
    const val showSolution = "Показать решение"
    const val realtimeOff = "Отображение статуса realtime выключено"
    const val addDatabase = "Добавить базу данных"
    const val onRealTime = "Мониторинг выбранной базы"
    const val memory = "Память"
    const val offRealTime = "Выключить мониторинг отображение состояния базы данных"
    const val enterDb = "Введите базу данных"
    const val enterDate = "Введите дату"
    const val checkPointBtn = "Проверить базу данных"
    const val checkPointDatetBtn = "Проверить базу данных в определённое время"
    const val backBtn = "Назад"
    const val stopBtn = "Остановить"
    const val changeMemory = "Изменить параметры памяти"
    const val monitorCommon = "Мониторинг всех баз"
    const val metrix = "Получить метрики"
    const val onEmoji = "✅"
    const val offEmoji = "❌"
    const val restartDb = "Убить транзакцию"
    const val DELIMITER = "@@@"
    const val vacuumClean = "Оптимизировать базу данных"
    const val effectiveCacheSize = "Размер кеша"
    const val maintenanceWorkMemory = "Основная зарезервированная память"
    const val workMemory = "Рабочая память"
    const val memoryLimit = "Лимит памяти"
    const val showMemory = "Показать параметры памяти"
}